"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RecoilRoot } from "recoil";
import Catalogue_ from "./components/ui/Catalogue_";
import Nav_ from "./components/navigation/Nav_";
import OverlayBtn_ from "./components/ui/OverlayBtn_";

const inter = Inter({ subsets: ["latin"] });

// const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <title>WhoseInn 3.0</title>
      <head>
        <script
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB3x0RxMZbl6LRapAhKlegw6Xmp9rupr0g&libraries=places"
          async
          defer
        ></script>
      </head>
      <body className={`${inter.className} overflow-hidden`}>
        <RecoilRoot>
          {children}
          <Catalogue_ />
          <div
            className={`min-w-8 h-[360px] px-4 mb-5 fixed bottom-0 flex flex-col justify-center items-center transition-all duration-200`}
          >
            <Nav_ />
          </div>
          <Test_ />
          <OverlayBtn_ />
        </RecoilRoot>
      </body>
    </html>
  );
}

interface Test_Props {}

const Test_ = ({}: Test_Props) => {
  async function createIndexAndEmbeddings() {
    try {
      const result = await fetch("/api/setup", {
        method: "POST",
      });
      const json = await result.json();
      console.log("result: ", json);
    } catch (err) {
      console.log("err:", err);
    }
  }
  return (
    <div
      className={`w-[85px] h-[85px] flex flex-col justify-end items-end pr-2 absolute top-1 left-1 rounded text-white font-black text-[20px] bg-black/80 cursor-pointer`}
      onClick={() => {
        createIndexAndEmbeddings();
        console.log("working..");
      }}
    >
      .W
    </div>
  );
};
